// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Models;

namespace WebApplication1.Migrations
{
    [DbContext(typeof(ApplicationDatabaseContext))]
    partial class ApplicationDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-preview3-35497")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication1.Models.TodoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Completed");

                    b.Property<string>("Task")
                        .HasMaxLength(256);

                    b.Property<string>("TodoItemKeyContainerKey");

                    b.HasKey("Id");

                    b.HasIndex("TodoItemKeyContainerKey");

                    b.ToTable("TodoItem");
                });

            modelBuilder.Entity("WebApplication1.Models.TodoItemKeyContainer", b =>
                {
                    b.Property<string>("Key")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Key");

                    b.ToTable("TodoItems");
                });

            modelBuilder.Entity("WebApplication1.Models.TodoItem", b =>
                {
                    b.HasOne("WebApplication1.Models.TodoItemKeyContainer")
                        .WithMany("Tasks")
                        .HasForeignKey("TodoItemKeyContainerKey");
                });
        }
    }
}
